name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -v .

    - name: Run Nancy against Self (gomod)
      run: go list -m all | ./nancy

    - name: Run Nancy against Self (dep)
      run: ./nancy Gopkg.lock
