name: Nancy PRs
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
          run: go build -v .

  test:
    name: Test
    steps:
      - name: Test
        run: go test -v .

  validate:
    name: Validate
    steps:
      - name: Nancy for GitHub Actions (gomod)
          uses: sonatype-nexus-community/nancy-github-action@1.0.0
          with:
            # This is the path to the go.sum or Gopkg.lock file.
            target: go.sum

      - name: Nancy for GitHub Actions (dep)
          uses: sonatype-nexus-community/nancy-github-action@1.0.0
          with:
            # This is the path to the go.sum or Gopkg.lock file.
            target: Gopkg.lock
